INSERT INTO Productos (nombre, descripcion, precio, stock) VALUES
('Camiseta básica blanca', 'Camiseta de algodón básica blanca de manga corta', 12.99, 50),
('Jeans ajustados negros', 'Jeans ajustados negros de tiro medio', 39.99, 30),
('Chaqueta de cuero marrón', 'Chaqueta de cuero marrón de corte ajustado', 149.99, 10),
('Zapatillas deportivas blancas', 'Zapatillas deportivas blancas de cuero y tela', 49.99, 25),
('Suéter de lana gris', 'Suéter de lana gris con cuello redondo', 59.99, 20),
('Vestido maxi floral', 'Vestido maxi floral de manga corta', 89.99, 15),
('Pantalones cortos de mezclilla', 'Pantalones cortos de mezclilla azul oscuro con bordado', 29.99, 35),
('Camisa de vestir blanca', 'Camisa de vestir blanca de algodón con cuello italiano', 79.99, 12),
('Botines de cuero negro', 'Botines de cuero negro con tacón bajo', 119.99, 8),
('Falda midi plisada', 'Falda midi plisada de satén rosa pálido', 69.99, 18),
('Chaqueta de mezclilla negra', 'Chaqueta de mezclilla negra con bordados florales', 99.99, 7),
('Camiseta gráfica', 'Camiseta de algodón con estampado gráfico y cuello redondo', 19.99, 40),
('Leggings negros', 'Leggings negros de compresión', 29.99, 30),
('Jersey de cuello alto', 'Jersey de lana de cuello alto gris', 79.99, 12),
('Pantalones de chándal', 'Pantalones de chándal de algodón gris', 39.99, 25),
('Abrigo de lana gris', 'Abrigo de lana gris con cinturón', 129.99, 8),
('Top sin mangas', 'Top sin mangas de seda rojo oscuro', 49.99, 20),
('Camiseta de rayas', 'Camiseta de algodón con rayas azul y blanca', 24.99, 35),
('Blusa de seda', 'Blusa de seda blanca con cuello alto', 89.99, 15),
('Chaqueta de bombardero', 'Chaqueta de bombardero de cuero negro con forro de piel', 199.99, 5),
('Camisa de mezclilla', 'Camisa de mezclilla de manga larga y corte regular', 69.99, 18),
('Pantalones de cuero', 'Pantalones de cuero negro de tiro alto', 149.99, 10),
('Vestido de cóctel negro', 'Vestido de cóctel negro con cuello halter', 129.99, 8);
